# Sample workflow for building and deploying an Astro site to GitHub Pages
name: Deploy Astro site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  BUILD_PATH: "." # Default build path

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Detect package manager
        id: detect-package-manager
        run: |
          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
            echo "manager=yarn" >> $GITHUB_ENV
            echo "install_command=install --frozen-lockfile" >> $GITHUB_ENV
            echo "runner=yarn" >> $GITHUB_ENV
            echo "lockfile=yarn.lock" >> $GITHUB_ENV
          elif [ -f "${{ github.workspace }}/package.json" ]; then
            echo "manager=npm" >> $GITHUB_ENV
            echo "install_command=ci" >> $GITHUB_ENV
            echo "runner=npx --yes" >> $GITHUB_ENV
            echo "lockfile=package-lock.json" >> $GITHUB_ENV
          else
            echo "Unable to determine package manager. Exiting."
            exit 1
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: ${{ env.manager }}
          cache-dependency-path: ${{ env.BUILD_PATH }}/${{ env.lockfile }}

      - name: Setup GitHub Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Install dependencies
        run: ${{ env.manager }} ${{ env.install_command }}
        working-directory: ${{ env.BUILD_PATH }}

      - name: Verify Astro installation
        run: npm list astro || npm install astro@latest
        working-directory: ${{ env.BUILD_PATH }}

      - name: Build with Astro
        run: |
          ${{ env.runner }} astro build \
            --site "${{ steps.pages.outputs.origin }}" \
            --base "${{ steps.pages.outputs.base_path }}"
        working-directory: ${{ env.BUILD_PATH }}

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.BUILD_PATH }}/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
